name: Deploy Automático na AWS

# O robô só vai rodar quando houver um 'git push' na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Baixa o código do seu repositório para o ambiente do GitHub
      - name: Checkout do código
        uses: actions/checkout@v4

      # Step 2: Conecta na AWS via SSH e atualiza o arquivo HTML
      - name: Copiar index.html para o Servidor via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "index.html"
          target: "/home/ubuntu/super-laboratorio/site-links/"

      # Step 3: Reinicia o Nginx para aplicar as alterações instantaneamente
      - name: Reiniciar o Porteiro Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/super-laboratorio
            docker compose restart porteiro-nginx